listen_addresses = '*'
ssl = on
ssl_cert_file = '/var/lib/postgresql/tls/postgres.crt'
ssl_key_file = '/var/lib/postgresql/tls/postgres.key'
hba_file = '/etc/postgresql/pg_hba.hardening.conf'
wal_level = replica
archive_mode = on
archive_command = 'test ! -f /wal_archive/%f && cp %p /wal_archive/%f'
archive_timeout = 300
max_wal_senders = 5
