apiVersion: 1

datasources:
  - name: Inova Postgres
    uid: inova-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: inova
    isDefault: true
    editable: false
    jsonData:
      database: inova_platform
      sslmode: $GF_POSTGRES_SSLMODE
      postgresVersion: 1600
    secureJsonData:
      password: $POSTGRES_PASSWORD
